name: kakula
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # help in the math expression
  math_expressions: ^2.3.1

  # change project BundleId
  rename: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # generate luncer icon
  flutter_launcher_icons: "^0.9.2"

  # native splash screen
  flutter_native_splash: ^2.2.4

  # contains a set of recommended lints to encourage good coding practices.
  flutter_lints: ^2.0.0

flutter_icons:
  ios: false
  android: "launcher_icon"
  image_path: "assets/img/ic_launcher.png"

flutter_native_splash:
  ios: false
  web: false
  color: "#22252d"
  fullscreen: true
  image: assets/img/kakula.png

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/img/

# To add fonts to your application
fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf